extends: substitution
message: "Use '%s' instead of '%s'"
level: warning
ignorecase: false

# swap maps tokens in form of bad: good
swap:
  writetechhub: WriteTech Hub
  vale: Vale
  web-site: website
  e-mail: email
  sdk: SDK
  api: API
  Github: GitHub
  wordpress: WordPress
