name: Install Documentation Tools

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  install-tools:
    name: Install Vale and Spectral
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Vale
        run: |
          echo "Installing Vale..."
          # Download and install Vale
          curl -sfL https://install.goreleaser.com/github.com/errata-ai/vale.sh | sh -s -- -b /usr/local/bin v2.28.0
          vale --version
          
      - name: Install Spectral CLI
        run: |
          echo "Installing Spectral CLI..."
          npm install -g @stoplight/spectral-cli
          spectral --version
          
      - name: Install Redocly CLI
        run: |
          echo "Installing Redocly CLI..."
          npm install -g @redocly/cli
          redocly --version
          
      - name: Verify installations
        run: |
          echo "=== Tool Versions ==="
          echo "Vale version:"
          vale --version
          echo ""
          echo "Spectral version:"
          spectral --version
          echo ""
          echo "Redocly version:"
          redocly --version
          echo ""
          echo "Node.js version:"
          node --version
          echo ""
          echo "npm version:"
          npm --version
          
      - name: Test Vale configuration
        run: |
          echo "Testing Vale configuration..."
          vale --config=.vale.ini --help
          echo "Vale configuration loaded successfully"
          
      - name: Test Spectral configuration
        run: |
          echo "Testing Spectral configuration..."
          spectral --help
          echo "Spectral configuration loaded successfully"
          
      - name: List installed packages
        run: |
          echo "=== Installed npm packages ==="
          npm list -g --depth=0
          
      - name: Upload tool information
        uses: actions/upload-artifact@v4
        with:
          name: tool-versions
          path: |
            .github/workflows/
          retention-days: 30
          
      - name: Comment PR with installation status
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            
            try {
              const valeVersion = execSync('vale --version', { encoding: 'utf8' }).trim();
              const spectralVersion = execSync('spectral --version', { encoding: 'utf8' }).trim();
              const redoclyVersion = execSync('redocly --version', { encoding: 'utf8' }).trim();
              
              const comment = `## Documentation Tools Installation Status ✅
              
              **Tools successfully installed:**
              
              - **Vale**: ${valeVersion}
              - **Spectral**: ${spectralVersion}
              - **Redocly**: ${redoclyVersion}
              
              All documentation validation tools are ready for use! 🎉`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            } catch (error) {
              const comment = `## Documentation Tools Installation Status ❌
              
              **Installation failed:**
              
              \`\`\`
              ${error.message}
              \`\`\`
              
              Please check the workflow logs for details.`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            } 